from .expr import Var

a0 = Var('a0')
b0 = Var('b0')
c0 = Var('c0')
d0 = Var('d0')
e0 = Var('e0')
f0 = Var('f0')
g0 = Var('g0')
h0 = Var('h0')
i0 = Var('i0')
j0 = Var('j0')
k0 = Var('k0')
l0 = Var('l0')
m0 = Var('m0')
n0 = Var('n0')
o0 = Var('o0')
p0 = Var('p0')
q0 = Var('q0')
r0 = Var('r0')
s0 = Var('s0')
t0 = Var('t0')
u0 = Var('u0')
v0 = Var('v0')
w0 = Var('w0')
x0 = Var('x0')
y0 = Var('y0')
z0 = Var('z0')

a1 = Var('a1')
b1 = Var('b1')
c1 = Var('c1')
d1 = Var('d1')
e1 = Var('e1')
f1 = Var('f1')
g1 = Var('g1')
h1 = Var('h1')
i1 = Var('i1')
j1 = Var('j1')
k1 = Var('k1')
l1 = Var('l1')
m1 = Var('m1')
n1 = Var('n1')
o1 = Var('o1')
p1 = Var('p1')
q1 = Var('q1')
r1 = Var('r1')
s1 = Var('s1')
t1 = Var('t1')
u1 = Var('u1')
v1 = Var('v1')
w1 = Var('w1')
x1 = Var('x1')
y1 = Var('y1')
z1 = Var('z1')

a2 = Var('a2')
b2 = Var('b2')
c2 = Var('c2')
d2 = Var('d2')
e2 = Var('e2')
f2 = Var('f2')
g2 = Var('g2')
h2 = Var('h2')
i2 = Var('i2')
j2 = Var('j2')
k2 = Var('k2')
l2 = Var('l2')
m2 = Var('m2')
n2 = Var('n2')
o2 = Var('o2')
p2 = Var('p2')
q2 = Var('q2')
r2 = Var('r2')
s2 = Var('s2')
t2 = Var('t2')
u2 = Var('u2')
v2 = Var('v2')
w2 = Var('w2')
x2 = Var('x2')
y2 = Var('y2')
z2 = Var('z2')

A0 = Var('A0', first_order=False)
B0 = Var('B0', first_order=False)
C0 = Var('C0', first_order=False)
D0 = Var('D0', first_order=False)
E0 = Var('E0', first_order=False)
F0 = Var('F0', first_order=False)
G0 = Var('G0', first_order=False)
H0 = Var('H0', first_order=False)
I0 = Var('I0', first_order=False)
J0 = Var('J0', first_order=False)
K0 = Var('K0', first_order=False)
L0 = Var('L0', first_order=False)
M0 = Var('M0', first_order=False)
N0 = Var('N0', first_order=False)
O0 = Var('O0', first_order=False)
P0 = Var('P0', first_order=False)
Q0 = Var('Q0', first_order=False)
R0 = Var('R0', first_order=False)
S0 = Var('S0', first_order=False)
T0 = Var('T0', first_order=False)
U0 = Var('U0', first_order=False)
V0 = Var('V0', first_order=False)
W0 = Var('W0', first_order=False)
X0 = Var('X0', first_order=False)
Y0 = Var('Y0', first_order=False)
Z0 = Var('Z0', first_order=False)

A1 = Var('A1', first_order=False)
B1 = Var('B1', first_order=False)
C1 = Var('C1', first_order=False)
D1 = Var('D1', first_order=False)
E1 = Var('E1', first_order=False)
F1 = Var('F1', first_order=False)
G1 = Var('G1', first_order=False)
H1 = Var('H1', first_order=False)
I1 = Var('I1', first_order=False)
J1 = Var('J1', first_order=False)
K1 = Var('K1', first_order=False)
L1 = Var('L1', first_order=False)
M1 = Var('M1', first_order=False)
N1 = Var('N1', first_order=False)
O1 = Var('O1', first_order=False)
P1 = Var('P1', first_order=False)
Q1 = Var('Q1', first_order=False)
R1 = Var('R1', first_order=False)
S1 = Var('S1', first_order=False)
T1 = Var('T1', first_order=False)
U1 = Var('U1', first_order=False)
V1 = Var('V1', first_order=False)
W1 = Var('W1', first_order=False)
X1 = Var('X1', first_order=False)
Y1 = Var('Y1', first_order=False)
Z1 = Var('Z1', first_order=False)

A2 = Var('A2', first_order=False)
B2 = Var('B2', first_order=False)
C2 = Var('C2', first_order=False)
D2 = Var('D2', first_order=False)
E2 = Var('E2', first_order=False)
F2 = Var('F2', first_order=False)
G2 = Var('G2', first_order=False)
H2 = Var('H2', first_order=False)
I2 = Var('I2', first_order=False)
J2 = Var('J2', first_order=False)
K2 = Var('K2', first_order=False)
L2 = Var('L2', first_order=False)
M2 = Var('M2', first_order=False)
N2 = Var('N2', first_order=False)
O2 = Var('O2', first_order=False)
P2 = Var('P2', first_order=False)
Q2 = Var('Q2', first_order=False)
R2 = Var('R2', first_order=False)
S2 = Var('S2', first_order=False)
T2 = Var('T2', first_order=False)
U2 = Var('U2', first_order=False)
V2 = Var('V2', first_order=False)
W2 = Var('W2', first_order=False)
X2 = Var('X2', first_order=False)
Y2 = Var('Y2', first_order=False)
Z2 = Var('Z2', first_order=False)

