from .expr import Var

a0 = Var('a0', atom=True)
b0 = Var('b0', atom=True)
c0 = Var('c0', atom=True)
d0 = Var('d0', atom=True)
e0 = Var('e0', atom=True)
f0 = Var('f0', atom=True)
g0 = Var('g0', atom=True)
h0 = Var('h0', atom=True)
i0 = Var('i0', atom=True)
j0 = Var('j0', atom=True)
k0 = Var('k0', atom=True)
l0 = Var('l0', atom=True)
m0 = Var('m0', atom=True)
n0 = Var('n0', atom=True)
o0 = Var('o0', atom=True)
p0 = Var('p0', atom=True)
q0 = Var('q0', atom=True)
r0 = Var('r0', atom=True)
s0 = Var('s0', atom=True)
t0 = Var('t0', atom=True)
u0 = Var('u0', atom=True)
v0 = Var('v0', atom=True)
w0 = Var('w0', atom=True)
x0 = Var('x0', atom=True)
y0 = Var('y0', atom=True)
z0 = Var('z0', atom=True)

a1 = Var('a1', atom=True)
b1 = Var('b1', atom=True)
c1 = Var('c1', atom=True)
d1 = Var('d1', atom=True)
e1 = Var('e1', atom=True)
f1 = Var('f1', atom=True)
g1 = Var('g1', atom=True)
h1 = Var('h1', atom=True)
i1 = Var('i1', atom=True)
j1 = Var('j1', atom=True)
k1 = Var('k1', atom=True)
l1 = Var('l1', atom=True)
m1 = Var('m1', atom=True)
n1 = Var('n1', atom=True)
o1 = Var('o1', atom=True)
p1 = Var('p1', atom=True)
q1 = Var('q1', atom=True)
r1 = Var('r1', atom=True)
s1 = Var('s1', atom=True)
t1 = Var('t1', atom=True)
u1 = Var('u1', atom=True)
v1 = Var('v1', atom=True)
w1 = Var('w1', atom=True)
x1 = Var('x1', atom=True)
y1 = Var('y1', atom=True)
z1 = Var('z1', atom=True)

a2 = Var('a2', atom=True)
b2 = Var('b2', atom=True)
c2 = Var('c2', atom=True)
d2 = Var('d2', atom=True)
e2 = Var('e2', atom=True)
f2 = Var('f2', atom=True)
g2 = Var('g2', atom=True)
h2 = Var('h2', atom=True)
i2 = Var('i2', atom=True)
j2 = Var('j2', atom=True)
k2 = Var('k2', atom=True)
l2 = Var('l2', atom=True)
m2 = Var('m2', atom=True)
n2 = Var('n2', atom=True)
o2 = Var('o2', atom=True)
p2 = Var('p2', atom=True)
q2 = Var('q2', atom=True)
r2 = Var('r2', atom=True)
s2 = Var('s2', atom=True)
t2 = Var('t2', atom=True)
u2 = Var('u2', atom=True)
v2 = Var('v2', atom=True)
w2 = Var('w2', atom=True)
x2 = Var('x2', atom=True)
y2 = Var('y2', atom=True)
z2 = Var('z2', atom=True)

A0 = Var('A0')
B0 = Var('B0')
C0 = Var('C0')
D0 = Var('D0')
E0 = Var('E0')
F0 = Var('F0')
G0 = Var('G0')
H0 = Var('H0')
I0 = Var('I0')
J0 = Var('J0')
K0 = Var('K0')
L0 = Var('L0')
M0 = Var('M0')
N0 = Var('N0')
O0 = Var('O0')
P0 = Var('P0')
Q0 = Var('Q0')
R0 = Var('R0')
S0 = Var('S0')
T0 = Var('T0')
U0 = Var('U0')
V0 = Var('V0')
W0 = Var('W0')
X0 = Var('X0')
Y0 = Var('Y0')
Z0 = Var('Z0')

A1 = Var('A1')
B1 = Var('B1')
C1 = Var('C1')
D1 = Var('D1')
E1 = Var('E1')
F1 = Var('F1')
G1 = Var('G1')
H1 = Var('H1')
I1 = Var('I1')
J1 = Var('J1')
K1 = Var('K1')
L1 = Var('L1')
M1 = Var('M1')
N1 = Var('N1')
O1 = Var('O1')
P1 = Var('P1')
Q1 = Var('Q1')
R1 = Var('R1')
S1 = Var('S1')
T1 = Var('T1')
U1 = Var('U1')
V1 = Var('V1')
W1 = Var('W1')
X1 = Var('X1')
Y1 = Var('Y1')
Z1 = Var('Z1')

A2 = Var('A2')
B2 = Var('B2')
C2 = Var('C2')
D2 = Var('D2')
E2 = Var('E2')
F2 = Var('F2')
G2 = Var('G2')
H2 = Var('H2')
I2 = Var('I2')
J2 = Var('J2')
K2 = Var('K2')
L2 = Var('L2')
M2 = Var('M2')
N2 = Var('N2')
O2 = Var('O2')
P2 = Var('P2')
Q2 = Var('Q2')
R2 = Var('R2')
S2 = Var('S2')
T2 = Var('T2')
U2 = Var('U2')
V2 = Var('V2')
W2 = Var('W2')
X2 = Var('X2')
Y2 = Var('Y2')
Z2 = Var('Z2')

